# Connector and global credential references captured during build.
# Used with globalCredentialsPlan.properties at deploy time.

application.name=SwiggyExpenseApprovalApp
application.version=1.0


# Connector CheckApprovalRestService
connector.71dfa6ed-06e4-415d-b248-a8c90a0d8da0.name=CheckApprovalRestService
connector.71dfa6ed-06e4-415d-b248-a8c90a0d8da0.type=REST
connector.71dfa6ed-06e4-415d-b248-a8c90a0d8da0.securityType=APPLICATION
connector.71dfa6ed-06e4-415d-b248-a8c90a0d8da0.baseUrl=https://postman-echo.com:443

